//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Werewolves.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Werewolves.Core.Resources.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input received (Logic not implemented)..
        /// </summary>
        internal static string Debug_InputReceivedPlaceholder {
            get {
                return ResourceManager.GetString("Debug_InputReceivedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session with ID {0} not found..
        /// </summary>
        internal static string Exception_GameSessionNotFound {
            get {
                return ResourceManager.GetString("Exception_GameSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide at least as many roles as players..
        /// </summary>
        internal static string Exception_NotEnoughRoles {
            get {
                return ResourceManager.GetString("Exception_NotEnoughRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player names list cannot be null, empty, or contain empty names..
        /// </summary>
        internal static string Exception_PlayerNamesInvalid {
            get {
                return ResourceManager.GetString("Exception_PlayerNamesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night 1 begins. Call the first night role..
        /// </summary>
        internal static string Instruction_Night1Start {
            get {
                return ResourceManager.GetString("Instruction_Night1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instruction pending..
        /// </summary>
        internal static string Instruction_NoInstructionPending {
            get {
                return ResourceManager.GetString("Instruction_NoInstructionPending", resourceCulture);
            }
        }
    }
}
