//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Werewolves.StateModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Werewolves.StateModels.Resources.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm everyone is asleep and there is silence.
        /// </summary>
        public static string ConfirmNightStarted {
            get {
                return ResourceManager.GetString("ConfirmNightStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to moderate and ensure everyone has a chance to speak and intervene. Confirm once the debate has finished..
        /// </summary>
        public static string DebateModeratorInstructions {
            get {
                return ResourceManager.GetString("DebateModeratorInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime debate begins. When finished, confirm to proceed to vote..
        /// </summary>
        public static string DebateStartsPrompt {
            get {
                return ResourceManager.GetString("DebateStartsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DefaultLogValue {
            get {
                return ResourceManager.GetString("DefaultLogValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over! {0}.
        /// </summary>
        public static string GameOverMessage {
            get {
                return ResourceManager.GetString("GameOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ready. Proceed to Night 1?.
        /// </summary>
        public static string GameStartPrompt {
            get {
                return ResourceManager.GetString("GameStartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following players were eliminated during the night: \n{0}.
        /// </summary>
        public static string MultipleVictimEliminatedAnnounce {
            get {
                return ResourceManager.GetString("MultipleVictimEliminatedAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The village goes to sleep..
        /// </summary>
        public static string NightStartsPrompt {
            get {
                return ResourceManager.GetString("NightStartsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player list cannot be empty..
        /// </summary>
        public static string PlayerListCannotBeEmpty {
            get {
                return ResourceManager.GetString("PlayerListCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the roles of the deceased in secret. Do not reveal them publicly at this stage..
        /// </summary>
        public static string RevealRolePromptSpecify {
            get {
                return ResourceManager.GetString("RevealRolePromptSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} goes to sleep..
        /// </summary>
        public static string RoleGoesToSleepSingle {
            get {
                return ResourceManager.GetString("RoleGoesToSleepSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainRole list cannot be empty..
        /// </summary>
        public static string RoleListCannotBeEmpty {
            get {
                return ResourceManager.GetString("RoleListCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please identify the players who are {0}..
        /// </summary>
        public static string RoleMultipleIdentificationPrompt {
            get {
                return ResourceManager.GetString("RoleMultipleIdentificationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please identify the player who is the {0}..
        /// </summary>
        public static string RoleSingleIdentificationPrompt {
            get {
                return ResourceManager.GetString("RoleSingleIdentificationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wakes up..
        /// </summary>
        public static string RoleWakesUp {
            get {
                return ResourceManager.GetString("RoleWakesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seer, choose a player whose identity you wish to discover..
        /// </summary>
        public static string SeerNightActionPrompt {
            get {
                return ResourceManager.GetString("SeerNightActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target {0} is NOT affiliated with the Werewolves (Thumbs Down)..
        /// </summary>
        public static string SeerResultNotWerewolfTeam {
            get {
                return ResourceManager.GetString("SeerResultNotWerewolfTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target {0} IS affiliated with the Werewolves (Thumbs Up)..
        /// </summary>
        public static string SeerResultWerewolfTeam {
            get {
                return ResourceManager.GetString("SeerResultWerewolfTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seer.
        /// </summary>
        public static string SeerRoleName {
            get {
                return ResourceManager.GetString("SeerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Villager.
        /// </summary>
        public static string SimpleVillagerRoleName {
            get {
                return ResourceManager.GetString("SimpleVillagerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Werewolf.
        /// </summary>
        public static string SimpleWerewolfRoleName {
            get {
                return ResourceManager.GetString("SimpleWerewolfRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} was eliminated during the night..
        /// </summary>
        public static string SingleVictimEliminatedAnnounce {
            get {
                return ResourceManager.GetString("SingleVictimEliminatedAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All werewolves eliminated..
        /// </summary>
        public static string VictoryConditionAllWerewolvesEliminated {
            get {
                return ResourceManager.GetString("VictoryConditionAllWerewolvesEliminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolves equal or outnumber villagers..
        /// </summary>
        public static string VictoryConditionWerewolvesOutnumber {
            get {
                return ResourceManager.GetString("VictoryConditionWerewolvesOutnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day vote phase. Please determine the outcome and report the single player eliminated (or report a tie)..
        /// </summary>
        public static string VoteStartsModeratorInstruction {
            get {
                return ResourceManager.GetString("VoteStartsModeratorInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting phase. Determine the outcome and report the eliminated player or if it was a tie..
        /// </summary>
        public static string VoteStartsPublicInstruction {
            get {
                return ResourceManager.GetString("VoteStartsPublicInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolves, wake up and choose one player to eliminate..
        /// </summary>
        public static string WerewolvesChooseVictimPrompt {
            get {
                return ResourceManager.GetString("WerewolvesChooseVictimPrompt", resourceCulture);
            }
        }
    }
}
